### ISSUE TITLE
Name 'browser' is not defined

### ISSUE THREAD

**Issue by dagrooms52** [TabMachine/KivyTest#2]
Open browser into title screen, click kivy logo in bottom-left by "powered by," produces following error:

```
main.py line 289 in open_browser
    browser.open_url(url)
NameError: name 'browser' is not defined
```

**Comment by mar7f7** [comment]
I fixed this issue. Im no longer using all that library stuff. I believe that the .pyc (python byte code was compiled for me and then wouldn't work for you guys), I have tested it on my computer and it works great. Also to activate the url, you have to click in between the image and the text. I haven't been able to line everything up correctly.
